# Generated by Django 4.2.7 on 2023-12-22 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_postagemforum_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postagemforum',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
